### PR TITLE
Fix registry url reference type

### LINKED ISSUE #83: modify registry url use reference type
**What would you like to be added**:
 make registry url use reference type

**Why is this needed**:

### PR DESCRIPTION
**Pull request by xiaoliu10**
**What this PR does**:
 upgrade  dubbo go v1.5.5-rc1 than common.URL use reference type
so modify dubbo go proxy url value type 

**Which issue(s) this PR fixes**:

Fixes #83

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by cityiron — APPROVED** [review]

File: pkg/registry/consul.go [hunk 1]
```diff
@@ -70,7 +70,7 @@ func (crl *ConsulRegistryLoad) GetCluster() (string, error) {
 	return crl.cluster, nil
 }
 
-func (crl *ConsulRegistryLoad) transfer2Url(service consul.AgentService) (common.URL, error) {
+func (crl *ConsulRegistryLoad) transfer2Url(service consul.AgentService) (*common.URL, error) {
```
Comment (zhangshen023) [inline pkg/registry/consul.go:73]: IMO, less pointer may be better

Comment (xiaoliu10) [reply pkg/registry/consul.go:73]: in dubbo go v1.5.5-rc1,  common.Url was chanaged to a reference type, and there is a lock in the url , If I evaluate it (*URL), I get an error, can not pass linter

Comment (zhangshen023) [reply pkg/registry/consul.go:73]: OK

**Review by zhangshen023 — APPROVED** [review]

**Review by AlexStocks — APPROVED** [review]
